import { expect, test, type Locator, type Page } from '@playwright/test'

const formatDocument = async (page: Page, editor: Locator): Promise<void> => {
  await editor.locator('.EditorRow').first().click({ button: 'right' })
  await page.getByRole('menuitem', { exact: true, name: 'Format Document' }).click()
  await expect(page.getByRole('menuitem', { exact: true, name: 'Format Document' })).toBeHidden()
}

test('diagnostics track TODO markers as the preview document changes', async ({ page }) => {
  await page.goto('/extension-samples/diagnostic-provider/')
  const editor = page.locator('#preview-ide .Editor')
  await expect(editor.locator('.DiagnosticError')).toHaveCount(2, { timeout: 30_000 })
  const problems = page.locator('#preview-ide .Problems')
  await expect(problems).toBeVisible()
  await expect(problems.getByText('Replace TODO with a setting value.', { exact: true })).toHaveCount(2)
  await expect(page.locator('#source-ide .Problems')).toBeHidden()
  await editor.locator('textarea').focus()
  await page.keyboard.press('Control+a')
  await page.keyboard.insertText('color=blue\nsize=large\n')
  await expect(editor.locator('.DiagnosticError')).toHaveCount(0)
  await page.keyboard.press('Control+a')
  await page.keyboard.insertText('color=TODO TODO\n')
  await expect(editor.locator('.DiagnosticError')).toHaveCount(2)
  await expect(page.locator('#source-ide .DiagnosticError')).toHaveCount(0)
})

test('completion filters a typed prefix and inserts the selected color', async ({ page }) => {
  await page.goto('/extension-samples/completion-provider/')
  const editor = page.locator('#preview-ide .Editor')
  await expect(editor).toContainText('color=', { timeout: 30_000 })
  const items = page.locator('.EditorCompletionItem')
  await expect(items).toHaveText(['blue', 'green', 'red'])
  await expect(page.locator('#preview-status')).toHaveText('Preview ready')
  await expect(page.locator('#source-ide .Editor')).toContainText('registerCompletionProvider')
  await page.keyboard.press('Escape')
  await page.keyboard.insertText('gr')
  await page.keyboard.press('Control+Space')
  await expect(items).toHaveText(['green'])
  await page.keyboard.press('Enter')
  await expect(editor.locator('.EditorRow').first()).toHaveText('color=green')
  await expect(page.locator('.EditorCompletion')).toBeHidden()
})

test('hover shows documentation only for a recognized word', async ({ page }) => {
  await page.goto('/extension-samples/hover-provider/')
  const editor = page.locator('#preview-ide .Editor')
  await expect(editor).toContainText('blue green red unknown', { timeout: 30_000 })
  await expect(page.locator('.EditorHover')).toContainText('Blue: the color of a clear sky.')
  await expect(page.locator('#preview-status')).toHaveText('Preview ready')
  await page.keyboard.press('Escape')
  await page.keyboard.press('End')
  await page.keyboard.press('ArrowLeft')
  await page.keyboard.press('Control+h')
  await expect(page.locator('.EditorHover')).toBeHidden()
})

test('formatting normalizes settings and can be undone', async ({ page }) => {
  await page.goto('/extension-samples/formatting-provider/')
  const editor = page.locator('#preview-ide .Editor')
  await expect(editor).toContainText('color=blue', { timeout: 30_000 })
  await editor.locator('textarea').focus()
  await formatDocument(page, editor)
  await expect(editor.locator('.EditorRow')).toHaveText(['color = blue', 'size = large', ''])
  await formatDocument(page, editor)
  await expect(editor.locator('.EditorRow')).toHaveText(['color = blue', 'size = large', ''])
  await editor.locator('textarea').focus()
  await page.keyboard.press('Control+z')
  await expect(editor.locator('.EditorRow')).toHaveText(['  color=blue  ', 'size =large', ''])
})
