import { expect, test } from '@playwright/test'
import { runCommand } from './RunCommand.ts'

test('diagnostics track TODO markers as the preview document changes', async ({ page }) => {
  await page.goto('/extension-samples/diagnostic-provider/')
  const editor = page.locator('#preview-ide .Editor')
  await expect(editor.locator('.DiagnosticError')).toHaveCount(2, { timeout: 30_000 })
  await editor.locator('textarea').focus()
  await page.keyboard.press('Control+a')
  await page.keyboard.insertText('color=blue\nsize=large\n')
  await expect(editor.locator('.DiagnosticError')).toHaveCount(0)
  await page.keyboard.press('Control+a')
  await page.keyboard.insertText('color=TODO TODO\n')
  await expect(editor.locator('.DiagnosticError')).toHaveCount(2)
  await expect(page.locator('#source-ide .DiagnosticError')).toHaveCount(0)
})

test('completion filters a typed prefix and inserts the selected color', async ({ page }) => {
  await page.goto('/extension-samples/completion-provider/')
  const editor = page.locator('#preview-ide .Editor')
  await expect(editor).toContainText('color=', { timeout: 30_000 })
  await editor.locator('textarea').focus()
  await page.keyboard.press('Control+Home')
  await page.keyboard.press('End')
  await page.keyboard.press('Control+Space')
  const items = page.locator('.EditorCompletionItem')
  await expect(items).toHaveText(['blue', 'green', 'red'])
  await page.keyboard.press('Escape')
  await page.keyboard.insertText('gr')
  await page.keyboard.press('Control+Space')
  await expect(items).toHaveText(['green'])
  await page.keyboard.press('Enter')
  await expect(editor.locator('.EditorRow').first()).toHaveText('color=green')
  await expect(page.locator('.EditorCompletion')).toBeHidden()
})

test('hover shows documentation only for a recognized word', async ({ page }) => {
  await page.goto('/extension-samples/hover-provider/')
  const editor = page.locator('#preview-ide .Editor')
  await expect(editor).toContainText('blue green red unknown', { timeout: 30_000 })
  await editor.locator('textarea').focus()
  await page.keyboard.press('Control+Home')
  await page.keyboard.press('Control+h')
  await expect(page.locator('.EditorHover')).toContainText('Blue: the color of a clear sky.')
  await page.keyboard.press('Escape')
  await page.keyboard.press('End')
  await page.keyboard.press('ArrowLeft')
  await page.keyboard.press('Control+h')
  await expect(page.locator('.EditorHover')).toBeHidden()
})

test('formatting normalizes settings and can be undone', async ({ page }) => {
  await page.goto('/extension-samples/formatting-provider/')
  const editor = page.locator('#preview-ide .Editor')
  await expect(editor).toContainText('color=blue', { timeout: 30_000 })
  await editor.locator('textarea').focus()
  await runCommand(page, 'Format Document')
  await expect(editor.locator('.EditorRow')).toHaveText(['color = blue', 'size = large', ''])
  await runCommand(page, 'Format Document')
  await expect(editor.locator('.EditorRow')).toHaveText(['color = blue', 'size = large', ''])
  await page.keyboard.press('Control+z')
  await expect(editor.locator('.EditorRow')).toHaveText(['  color=blue  ', 'size =large', ''])
})
