import { expect, test } from '@playwright/test'
import { runCommand } from './RunCommand.ts'

test('status bar item updates after selection and preserves its value on cancellation', async ({ page }) => {
  await page.goto('/extension-samples/status-bar-item/')
  const item = page.locator('#preview-ide .StatusBarItem').filter({ hasText: 'Environment:' })
  await expect(item).toHaveText('Environment: Development', { timeout: 30_000 })
  await expect(page.locator('#source-ide .StatusBar')).toBeHidden()
  await item.click()
  await page.locator('#preview-ide .QuickPick').getByRole('option').filter({ hasText: 'Staging' }).click()
  await expect(item).toHaveText('Environment: Staging')
  await item.click()
  await expect(page.locator('#preview-ide .QuickPick')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.locator('#preview-ide .QuickPick')).toBeHidden()
  await expect(item).toHaveText('Environment: Staging')
})

test('output channel appends successive builds and clears its logs', async ({ page }) => {
  await page.goto('/extension-samples/output-channel/')
  const output = page.locator('#preview-ide .OutputContent')
  await expect(output).toContainText('Ready.', { timeout: 30_000 })
  await runCommand(page, 'Sample: Run Build')
  await expect(output).toContainText('Build 1: starting\nCompiling example.sample... done\nBuild succeeded.')
  await runCommand(page, 'Sample: Run Build')
  await expect(output).toContainText('Build 1: starting')
  await expect(output).toContainText('Build 2: starting')
  await runCommand(page, 'Sample: Clear Build Output')
  await expect(output).toHaveText('')
  await expect(page.locator('#source-ide .OutputContent')).toHaveCount(0)
})

test('definition navigation moves to the declaration and reports missing symbols', async ({ page }) => {
  await page.goto('/extension-samples/definition-provider/')
  await expect(page.locator('#preview-status')).toHaveText('Preview ready', { timeout: 30_000 })
  const editor = page.locator('#preview-ide .Editor')
  await editor.locator('textarea').focus()
  await page.keyboard.press('F12')
  await expect(editor.locator('.EditorCursor')).toHaveCSS('translate', /^[-\d.]+px(?: 0px)?$/)
  // Inserting at the resulting cursor proves that navigation reached the declaration.
  await page.keyboard.insertText('new_')
  await expect(editor.locator('.EditorRow').first()).toHaveText('let new_color = blue')
  await page.keyboard.press('Control+z')
  await page.keyboard.press('Control+End')
  await page.keyboard.press('ArrowUp')
  await page.keyboard.press('Home')
  await page.keyboard.press('ArrowRight')
  await page.keyboard.press('ArrowRight')
  await page.keyboard.press('ArrowRight')
  await page.keyboard.press('ArrowRight')
  await page.keyboard.press('ArrowRight')
  await page.keyboard.press('ArrowRight')
  await page.keyboard.press('ArrowRight')
  await page.keyboard.press('F12')
  await expect(page.locator('#preview-ide .EditorMessage')).toContainText('No definition found')
})

test('rename changes complete identifiers, supports undo, and can be cancelled', async ({ page }) => {
  await page.goto('/extension-samples/rename-provider/')
  await expect(page.locator('#preview-status')).toHaveText('Preview ready', { timeout: 30_000 })
  const editor = page.locator('#preview-ide .Editor')
  await editor.locator('textarea').focus()
  await page.keyboard.press('F2')
  const input = page.locator('#preview-ide .RenameInputBox')
  await expect(input).toBeVisible()
  await input.fill('shade')
  await page.keyboard.press('Enter')
  await expect(input).toBeHidden()
  await expect(editor.locator('.EditorRow')).toHaveText(['let shade = blue', 'let colorful = green', 'print(shade)', 'print(shade)', ''])
  await editor.locator('textarea').focus()
  await page.keyboard.press('Control+z')
  await expect(editor.locator('.EditorRow')).toHaveText(['let color = blue', 'let colorful = green', 'print(color)', 'print(color)', ''])
  await page.keyboard.press('F2')
  await expect(input).toBeVisible()
  await input.fill('cancelled')
  await page.keyboard.press('Escape')
  await expect(input).toBeHidden()
  await expect(editor).not.toContainText('cancelled')
})

test('organize imports sorts the import block and supports undo', async ({ page }) => {
  await page.goto('/extension-samples/code-actions/')
  await expect(page.locator('#preview-status')).toHaveText('Preview ready', { timeout: 30_000 })
  const editor = page.locator('#preview-ide .Editor')
  await editor.locator('textarea').focus()
  await page.keyboard.press('Shift+Alt+o')
  await expect(editor.locator('.EditorRow')).toHaveText(['import apple', 'import zebra', '', 'print(apple)', ''])
  await editor.locator('textarea').focus()
  await page.keyboard.press('Control+z')
  await expect(editor.locator('.EditorRow')).toHaveText(['import zebra', 'import apple', '', 'print(apple)', ''])
})
