import { expect, test } from '@playwright/test'

test('sidebar counter renders virtual DOM and responds to mouse and keyboard', async ({ page }) => {
  await page.goto('/extension-samples/sidebar-counter/')
  const preview = page.locator('#preview-ide')
  const counter = preview.locator('.SidebarCounter')
  const value = counter.getByRole('status')
  await expect(value).toHaveText('Count: 0', { timeout: 30_000 })
  await expect(preview.locator('.SideBar')).toContainText('Counter')
  await expect(page.locator('#source-ide .SidebarCounter')).toHaveCount(0)

  await counter.getByRole('button', { name: 'Increment' }).click()
  await expect(value).toHaveText('Count: 1')
  await counter.getByRole('button', { name: 'Increment' }).click()
  await expect(value).toHaveText('Count: 2')
  await counter.getByRole('button', { name: 'Decrement' }).click()
  await expect(value).toHaveText('Count: 1')
  await counter.getByRole('button', { name: 'Decrement' }).press('Enter')
  await expect(value).toHaveText('Count: 0')
  await counter.getByRole('button', { name: 'Decrement' }).press('Space')
  await expect(value).toHaveText('Count: -1')
})

test('editing the counter updates the preview and reset restores the sample', async ({ page }) => {
  await page.goto('/extension-samples/sidebar-counter/')
  await expect(page.locator('body')).toHaveAttribute('data-playground-ready', 'true', { timeout: 30_000 })
  const source = page.locator('#source-ide')
  const counter = page.locator('#preview-ide .SidebarCounter')
  await counter.getByRole('button', { name: 'Increment' }).click()
  await expect(counter.getByRole('status')).toHaveText('Count: 1')

  const response = await page.request.get('/extension-samples/samples/sidebar-counter/files.json')
  const files = await response.json()
  await source.locator('.Editor textarea').focus()
  await page.keyboard.press('Control+a')
  await page.keyboard.insertText(files['/src/main.ts'].replace('count += 1', 'count += 2'))
  await expect(source.locator('.Editor')).toContainText('count += 2')
  await page.keyboard.press('Control+s')
  await expect(page.locator('body')).toHaveAttribute('data-preview-revision', '2')
  await expect(counter.getByRole('status')).toHaveText('Count: 0')
  await counter.getByRole('button', { name: 'Increment' }).click()
  await expect(counter.getByRole('status')).toHaveText('Count: 2')

  await page.getByRole('button', { name: 'Reset sample' }).click()
  await expect(page.locator('body')).toHaveAttribute('data-preview-revision', '3')
  await expect(counter.getByRole('status')).toHaveText('Count: 0')
  await counter.getByRole('button', { name: 'Increment' }).click()
  await expect(counter.getByRole('status')).toHaveText('Count: 1')
})
