import { expect, test } from '@playwright/test'

test('opens the real LVCE source-control view beside the sample source', async ({ page }) => {
  await page.goto('/extension-samples/source-control-provider/')
  const workbench = page.locator('#preview-ide')

  await expect(workbench.locator('.Editor')).toHaveCount(1, { timeout: 30_000 })
  await expect(page.locator('#source-ide .Editor .Token.KeywordImport').first()).toHaveText('import')
  await expect(workbench.locator('.SourceControl')).toContainText('Changes')
  await expect(workbench.locator('.SourceControl')).toContainText('README.md')
  await expect(workbench.locator('.SourceControl')).toContainText('main.ts')
  await expect(workbench.locator('.SourceControlBadge')).toHaveText('2')
  await expect(workbench.locator('.DecorationIcon')).toHaveCount(2)
  await expect(workbench.locator('.DecorationIcon').first()).toHaveJSProperty('naturalWidth', 16)
  await expect(workbench.locator('.TitleBar:visible, .ActivityBar:visible, .StatusBar:visible')).toHaveCount(0)
})

test('opens the manifest from Explorer and recovers from a missing decoration icon', async ({ page }) => {
  await page.goto('/extension-samples/source-control-provider/')
  const source = page.locator('#source-ide')
  const preview = page.locator('#preview-ide')
  await expect(preview.locator('.DecorationIcon')).toHaveCount(2, { timeout: 30_000 })
  await source.getByRole('treeitem', { exact: true, name: 'extension.json' }).click()
  await expect(source.getByRole('tab', { exact: true, name: 'extension.json Close' })).toBeVisible()
  await expect(source.locator('.Editor')).toContainText('icons/modified.svg')
  const response = await page.request.get('/extension-samples/samples/source-control-provider/files.json')
  const files = await response.json()
  await source.locator('.Editor textarea').focus()
  await page.keyboard.press('Control+a')
  await page.keyboard.insertText(files['/extension.json'].replace('icons/modified.svg', 'icons/missing.svg'))
  await expect(source.locator('.Editor')).toContainText('icons/missing.svg')
  await page.keyboard.press('Control+s')
  await expect(page.locator('#preview-status')).toContainText('Missing icon:')
  await expect(preview.locator('.DecorationIcon')).toHaveCount(2)
  await source.locator('.Editor textarea').focus()
  await page.keyboard.press('Control+a')
  await page.keyboard.insertText(files['/extension.json'])
  await expect(source.locator('.Editor')).toContainText('icons/modified.svg')
  await page.keyboard.press('Control+s')
  await expect(page.locator('#preview-status')).toHaveText('Preview ready')
  await expect(page.locator('body')).toHaveAttribute('data-preview-revision', '2')
  await expect(source.getByRole('tab', { exact: true, name: 'extension.json Close' })).toBeVisible()
})

test('edits an SVG decoration as source and reloads the image in the preview', async ({ page }) => {
  await page.goto('/extension-samples/source-control-provider/')
  const source = page.locator('#source-ide')
  const preview = page.locator('#preview-ide')
  await expect(page.locator('body')).toHaveAttribute('data-playground-ready', 'true', { timeout: 30_000 })
  const icon = preview.locator('.DecorationIcon').first()
  await expect(icon).toHaveJSProperty('naturalWidth', 16)
  const originalIconUrl = await icon.evaluate((element) => (element as HTMLImageElement).src)
  await source.getByRole('treeitem', { exact: true, name: 'icons' }).click()
  await source.getByRole('treeitem', { exact: true, name: 'modified.svg' }).click()
  await expect(source.locator('.Editor')).toContainText('<svg')
  await source.locator('.Editor textarea').focus()
  await page.keyboard.press('Control+a')
  await page.keyboard.insertText('<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"><circle cx="8" cy="8" r="6" fill="red"/></svg>')
  await expect(source.locator('.Editor')).toContainText('<circle')
  await page.keyboard.press('Control+s')
  await expect(page.locator('body')).toHaveAttribute('data-preview-revision', '2')
  await expect(icon).not.toHaveAttribute('src', originalIconUrl)
  await expect(icon).toHaveJSProperty('naturalWidth', 16)
  const svg = await icon.evaluate(async (element) => {
    const response = await fetch((element as HTMLImageElement).src)
    return response.text()
  })
  expect(svg).toContain('fill="red"')
  await expect(source.getByRole('tab', { name: 'modified.svg' })).toBeVisible()
})
